CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "first_name" varchar(150) NOT NULL);
CREATE TABLE IF NOT EXISTS "cmms_almacen" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(50) NOT NULL);
CREATE TABLE IF NOT EXISTS "cmms_empresa" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(250) NOT NULL);
CREATE TABLE IF NOT EXISTS "cmms_horariopreestablecido" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL UNIQUE, "operativo" bool NULL, "noOperativo" bool NULL);
CREATE TABLE IF NOT EXISTS "cmms_marca" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "cmms_puntodemedicion" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL, "descripcion" text NOT NULL);
CREATE TABLE IF NOT EXISTS "cmms_area" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL, "identificador" varchar(100) NULL, "principal_id" bigint NULL REFERENCES "cmms_area" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "cmms_categoria" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(50) NOT NULL, "principal_id" bigint NULL REFERENCES "cmms_categoria" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "cmms_diahorario" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "dia" varchar(1) NOT NULL, "horaInicio" time NOT NULL, "horaFinal" time NOT NULL, "horario_id" bigint NOT NULL REFERENCES "cmms_horariopreestablecido" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "cmms_material" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL, "descripcion" text NOT NULL, "tipo" varchar(20) NOT NULL, "codigo_de_barra" varchar(100) NULL, "marca_id" bigint NULL REFERENCES "cmms_marca" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "cmms_kit_materiales" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "kit_id" bigint NOT NULL REFERENCES "cmms_kit" ("id") DEFERRABLE INITIALLY DEFERRED, "material_id" bigint NOT NULL REFERENCES "cmms_material" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "cmms_modelo" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL, "categoria_id" bigint NULL REFERENCES "cmms_categoria" ("id") DEFERRABLE INITIALLY DEFERRED, "marca_id" bigint NOT NULL REFERENCES "cmms_marca" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "cmms_activo" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL, "no_inventario" varchar(100) NULL UNIQUE, "area_id" bigint NULL REFERENCES "cmms_area" ("id") DEFERRABLE INITIALLY DEFERRED, "marca_id" bigint NULL REFERENCES "cmms_marca" ("id") DEFERRABLE INITIALLY DEFERRED, "modelo_id" bigint NULL REFERENCES "cmms_modelo" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "cmms_activo_hojasderuta" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "activo_id" bigint NOT NULL REFERENCES "cmms_activo" ("id") DEFERRABLE INITIALLY DEFERRED, "hojaderuta_id" bigint NOT NULL REFERENCES "cmms_hojaderuta" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "cmms_movimientodeinventario" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "movimiento" varchar(100) NOT NULL, "cantidad" integer NOT NULL, "fecha_de_transaccion" datetime NOT NULL, "tipo_de_transaccion" varchar(20) NOT NULL, "almacen_id" bigint NULL REFERENCES "cmms_almacen" ("id") DEFERRABLE INITIALLY DEFERRED, "material_id" bigint NOT NULL REFERENCES "cmms_material" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "cmms_persona" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(250) NOT NULL, "dni" varchar(13) NULL, "empresa_id" bigint NULL REFERENCES "cmms_empresa" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "cmms_programacion" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL, "fechaDeInicio" datetime NOT NULL, "fecha_final" datetime NULL, "programado" bool NOT NULL, "HojaDeRuta_id" bigint NOT NULL REFERENCES "cmms_hojaderuta" ("id") DEFERRABLE INITIALLY DEFERRED, "horario_id" bigint NULL REFERENCES "cmms_horariopreestablecido" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "cmms_programacion_activos" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "programacion_id" bigint NOT NULL REFERENCES "cmms_programacion" ("id") DEFERRABLE INITIALLY DEFERRED, "activo_id" bigint NOT NULL REFERENCES "cmms_activo" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "cmms_programacion_areas" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "programacion_id" bigint NOT NULL REFERENCES "cmms_programacion" ("id") DEFERRABLE INITIALLY DEFERRED, "area_id" bigint NOT NULL REFERENCES "cmms_area" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "cmms_area_principal_id_d3eaa9de" ON "cmms_area" ("principal_id");
CREATE INDEX "cmms_categoria_principal_id_a1da7897" ON "cmms_categoria" ("principal_id");
CREATE INDEX "cmms_diahorario_horario_id_ff8a7a71" ON "cmms_diahorario" ("horario_id");
CREATE INDEX "cmms_material_marca_id_d02279d0" ON "cmms_material" ("marca_id");
CREATE UNIQUE INDEX "cmms_kit_materiales_kit_id_material_id_e576784b_uniq" ON "cmms_kit_materiales" ("kit_id", "material_id");
CREATE INDEX "cmms_kit_materiales_kit_id_b51a4a42" ON "cmms_kit_materiales" ("kit_id");
CREATE INDEX "cmms_kit_materiales_material_id_4756f028" ON "cmms_kit_materiales" ("material_id");
CREATE INDEX "cmms_modelo_categoria_id_2c5f14a3" ON "cmms_modelo" ("categoria_id");
CREATE INDEX "cmms_modelo_marca_id_8eed6f03" ON "cmms_modelo" ("marca_id");
CREATE INDEX "cmms_activo_area_id_9eb1084e" ON "cmms_activo" ("area_id");
CREATE INDEX "cmms_activo_marca_id_915510f2" ON "cmms_activo" ("marca_id");
CREATE INDEX "cmms_activo_modelo_id_d924d4a8" ON "cmms_activo" ("modelo_id");
CREATE UNIQUE INDEX "cmms_activo_hojasderuta_activo_id_hojaderuta_id_b11eb42d_uniq" ON "cmms_activo_hojasderuta" ("activo_id", "hojaderuta_id");
CREATE INDEX "cmms_activo_hojasderuta_activo_id_a071eea0" ON "cmms_activo_hojasderuta" ("activo_id");
CREATE INDEX "cmms_activo_hojasderuta_hojaderuta_id_c51b837f" ON "cmms_activo_hojasderuta" ("hojaderuta_id");
CREATE INDEX "cmms_movimientodeinventario_almacen_id_5569e4cc" ON "cmms_movimientodeinventario" ("almacen_id");
CREATE INDEX "cmms_movimientodeinventario_material_id_3b4dbcae" ON "cmms_movimientodeinventario" ("material_id");
CREATE INDEX "cmms_persona_empresa_id_c662e19c" ON "cmms_persona" ("empresa_id");
CREATE INDEX "cmms_programacion_HojaDeRuta_id_4b0324b8" ON "cmms_programacion" ("HojaDeRuta_id");
CREATE UNIQUE INDEX "cmms_programacion_activos_programacion_id_activo_id_9a5281d1_uniq" ON "cmms_programacion_activos" ("programacion_id", "activo_id");
CREATE INDEX "cmms_programacion_activos_programacion_id_1c5c914a" ON "cmms_programacion_activos" ("programacion_id");
CREATE INDEX "cmms_programacion_activos_activo_id_13a26415" ON "cmms_programacion_activos" ("activo_id");
CREATE UNIQUE INDEX "cmms_programacion_areas_programacion_id_area_id_a45ca558_uniq" ON "cmms_programacion_areas" ("programacion_id", "area_id");
CREATE INDEX "cmms_programacion_areas_programacion_id_8b14bc2b" ON "cmms_programacion_areas" ("programacion_id");
CREATE INDEX "cmms_programacion_areas_area_id_0c0e0950" ON "cmms_programacion_areas" ("area_id");
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "cmms_semana" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(2) NOT NULL, "fecha_inicial" date NOT NULL, "fecha_final" date NOT NULL);
CREATE TABLE IF NOT EXISTS "cmms_sistema" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL, "principal_id" bigint NULL REFERENCES "cmms_sistema" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "cmms_sistema_principal_id_92cdd95a" ON "cmms_sistema" ("principal_id");
CREATE TABLE IF NOT EXISTS "cmms_ordendetrabajo" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL, "fechaDeInicio" datetime NULL, "fechaDeFin" datetime NULL, "HojaDeRuta_id" bigint NULL REFERENCES "cmms_hojaderuta" ("id") DEFERRABLE INITIALLY DEFERRED, "area_id" bigint NULL REFERENCES "cmms_area" ("id") DEFERRABLE INITIALLY DEFERRED, "programacion_id" bigint NULL REFERENCES "cmms_programacion" ("id") DEFERRABLE INITIALLY DEFERRED, "Activo_id" bigint NULL REFERENCES "cmms_activo" ("id") DEFERRABLE INITIALLY DEFERRED, "horario_id" bigint NULL REFERENCES "cmms_horariopreestablecido" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "cmms_ordendetrabajo_HojaDeRuta_id_19f2f289" ON "cmms_ordendetrabajo" ("HojaDeRuta_id");
CREATE INDEX "cmms_ordendetrabajo_area_id_77655f4f" ON "cmms_ordendetrabajo" ("area_id");
CREATE INDEX "cmms_ordendetrabajo_programacion_id_01bd2f54" ON "cmms_ordendetrabajo" ("programacion_id");
CREATE TABLE IF NOT EXISTS "cmms_frecuencia" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(50) NOT NULL, "intervalo" integer NOT NULL, "color" varchar(7) NOT NULL);
CREATE INDEX "cmms_ordendetrabajo_Activo_id_9d7aa59f" ON "cmms_ordendetrabajo" ("Activo_id");
CREATE INDEX "cmms_programacion_horario_id_8cc7db5c" ON "cmms_programacion" ("horario_id");
CREATE INDEX "cmms_ordendetrabajo_horario_id_14ed6a2d" ON "cmms_ordendetrabajo" ("horario_id");
CREATE TABLE IF NOT EXISTS "cmms_kitdeherramientas_herramientas" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "kitdeherramientas_id" bigint NOT NULL REFERENCES "cmms_kitdeherramientas" ("id") DEFERRABLE INITIALLY DEFERRED, "herramienta_id" bigint NOT NULL REFERENCES "cmms_herramienta" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "cmms_kitdeherramientas_herramientas_kitdeherramientas_id_herramienta_id_71c4b32b_uniq" ON "cmms_kitdeherramientas_herramientas" ("kitdeherramientas_id", "herramienta_id");
CREATE INDEX "cmms_kitdeherramientas_herramientas_kitdeherramientas_id_7eeb98c6" ON "cmms_kitdeherramientas_herramientas" ("kitdeherramientas_id");
CREATE INDEX "cmms_kitdeherramientas_herramientas_herramienta_id_9ace0066" ON "cmms_kitdeherramientas_herramientas" ("herramienta_id");
CREATE TABLE IF NOT EXISTS "cmms_herramienta_categoria" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "herramienta_id" bigint NOT NULL REFERENCES "cmms_herramienta" ("id") DEFERRABLE INITIALLY DEFERRED, "categoria_id" bigint NOT NULL REFERENCES "cmms_categoria" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "cmms_herramienta_categoria_herramienta_id_categoria_id_12439c56_uniq" ON "cmms_herramienta_categoria" ("herramienta_id", "categoria_id");
CREATE INDEX "cmms_herramienta_categoria_herramienta_id_c353e11c" ON "cmms_herramienta_categoria" ("herramienta_id");
CREATE INDEX "cmms_herramienta_categoria_categoria_id_d44d6ce0" ON "cmms_herramienta_categoria" ("categoria_id");
CREATE TABLE IF NOT EXISTS "cmms_personal" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL, "apellido" varchar(100) NOT NULL, "dni" varchar(13) NOT NULL);
CREATE TABLE IF NOT EXISTS "cmms_unidad" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL, "abreviatura" varchar(10) NOT NULL);
CREATE TABLE IF NOT EXISTS "cmms_cuadrilla" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL);
CREATE TABLE IF NOT EXISTS "cmms_kit" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL, "descripcion" text NULL, "clave_kit" varchar(100) NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "cmms_kitdeherramientas" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL, "descripcion" text NULL, "clave_kit" varchar(100) NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "cmms_herramienta" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "marca_id" bigint NULL REFERENCES "cmms_marca" ("id") DEFERRABLE INITIALLY DEFERRED, "descripcion" text NULL, "unidad_id" bigint NULL REFERENCES "cmms_unidad" ("id") DEFERRABLE INITIALLY DEFERRED, "nombre" varchar(100) NOT NULL UNIQUE, "material_id" bigint NULL REFERENCES "cmms_material" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "cmms_herramienta_marca_id_07031a7f" ON "cmms_herramienta" ("marca_id");
CREATE INDEX "cmms_herramienta_unidad_id_80c088d2" ON "cmms_herramienta" ("unidad_id");
CREATE TABLE IF NOT EXISTS "cmms_menuitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "url" varchar(255) NOT NULL, "order" integer NOT NULL);
CREATE TABLE IF NOT EXISTS "cmms_cuadrilla_puestos" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "cuadrilla_id" bigint NOT NULL REFERENCES "cmms_cuadrilla" ("id") DEFERRABLE INITIALLY DEFERRED, "puesto_id" bigint NOT NULL REFERENCES "cmms_puesto" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "cmms_puesto" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL, "HorarioPreestablecido_id" bigint NULL REFERENCES "cmms_horariopreestablecido" ("id") DEFERRABLE INITIALLY DEFERRED, "descripcion" text NOT NULL);
CREATE UNIQUE INDEX "cmms_cuadrilla_puestos_cuadrilla_id_puesto_id_c996b26d_uniq" ON "cmms_cuadrilla_puestos" ("cuadrilla_id", "puesto_id");
CREATE INDEX "cmms_cuadrilla_puestos_cuadrilla_id_6d6641f7" ON "cmms_cuadrilla_puestos" ("cuadrilla_id");
CREATE INDEX "cmms_cuadrilla_puestos_puesto_id_42342e65" ON "cmms_cuadrilla_puestos" ("puesto_id");
CREATE INDEX "cmms_puesto_HorarioPreestablecido_id_8d00c5af" ON "cmms_puesto" ("HorarioPreestablecido_id");
CREATE INDEX "cmms_herramienta_material_id_f8b488c2" ON "cmms_herramienta" ("material_id");
CREATE TABLE IF NOT EXISTS "cmms_hojaderuta" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "descripcion" text NULL, "intervalo_id" bigint NULL REFERENCES "cmms_frecuencia" ("id") DEFERRABLE INITIALLY DEFERRED, "sistema_id" bigint NULL REFERENCES "cmms_sistema" ("id") DEFERRABLE INITIALLY DEFERRED, "kitDeHerramientas_id" bigint NULL REFERENCES "cmms_kitdeherramientas" ("id") DEFERRABLE INITIALLY DEFERRED, "clave_rutina" varchar(100) NULL UNIQUE, "nombre" varchar(100) NOT NULL UNIQUE);
CREATE INDEX "cmms_hojaderuta_intervalo_id_a6a53bb7" ON "cmms_hojaderuta" ("intervalo_id");
CREATE INDEX "cmms_hojaderuta_sistema_id_0565a0d0" ON "cmms_hojaderuta" ("sistema_id");
CREATE INDEX "cmms_hojaderuta_kitDeHerramientas_id_421e59a9" ON "cmms_hojaderuta" ("kitDeHerramientas_id");
CREATE TABLE IF NOT EXISTS "cmms_pasoshojaderuta" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "paso" varchar(100) NOT NULL, "tiempo" integer NULL, "hojaderuta_id" bigint NOT NULL REFERENCES "cmms_hojaderuta" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "cmms_pasoshojaderuta_hojaderuta_id_0b93ef6c" ON "cmms_pasoshojaderuta" ("hojaderuta_id");
CREATE UNIQUE INDEX "cmms_pasoshojaderuta_paso_hojaderuta_id_8b52c13b_uniq" ON "cmms_pasoshojaderuta" ("paso", "hojaderuta_id");
