# Generated by Django 5.1.3 on 2025-01-30 06:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('intervalo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HorarioPreestablecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('operativo', models.BooleanField(blank=True, null=True)),
                ('noOperativo', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDeMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Plan de Mantenimiento',
                'verbose_name_plural': 'Planes de Mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='PuntoDeMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('identificador', models.CharField(blank=True, max_length=100, null=True)),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cmms.area')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='cmms.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='HojaDeRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(null=True)),
                ('frecuencia', models.CharField(choices=[('Mensual', 'Mensual'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], default='Mensual', max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('areas', models.ManyToManyField(blank=True, related_name='hojas_de_ruta', to='cmms.area')),
                ('intervalo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.frecuencia')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms.horariopreestablecido')),
                ('plandemantenimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.plandemantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='DiaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], max_length=1)),
                ('horaInicio', models.TimeField()),
                ('horaFinal', models.TimeField()),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_horarios', to='cmms.horariopreestablecido')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('REPUESTO', 'Repuesto'), ('EPP', 'Equipo de Protección Personal'), ('HERRAMIENTA', 'herramienta')], max_length=20)),
                ('codigo_de_barra', models.CharField(max_length=100, null=True)),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True)),
                ('materiales', models.ManyToManyField(to='cmms.material')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('no_inventario', models.CharField(max_length=100, null=True, unique=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.area')),
                ('hojasderuta', models.ManyToManyField(blank=True, related_name='hojaderuta', to='cmms.hojaderuta')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.marca')),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoDeInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fecha_de_transaccion', models.DateTimeField()),
                ('tipo_de_transaccion', models.CharField(choices=[('INGRESO', 'Ingreso de Material'), ('AJUSTE', 'Ajuste de Inventario'), ('DESPACHO', 'Despacho de Material')], default='INGRESO', max_length=20)),
                ('almacen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.almacen', verbose_name='Almacen')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.material')),
            ],
        ),
        migrations.CreateModel(
            name='PasosHojaDeRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso', models.CharField(max_length=100)),
                ('tiempo', models.IntegerField(null=True)),
                ('hojaderuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.hojaderuta')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('dni', models.CharField(max_length=13, null=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fechaDeInicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateTimeField(null=True)),
                ('programado', models.BooleanField(default=False)),
                ('HojaDeRuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.hojaderuta')),
                ('activos', models.ManyToManyField(blank=True, related_name='programacion', to='cmms.activo')),
                ('areas', models.ManyToManyField(blank=True, related_name='programacion', to='cmms.area')),
            ],
            options={
                'verbose_name': 'Programación',
                'verbose_name_plural': 'Programaciones',
            },
        ),
    ]
