# Generated by Django 5.1.3 on 2025-01-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0002_semana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hojaderuta',
            name='plandemantenimiento',
        ),
        migrations.DeleteModel(
            name='PlanDeMantenimiento',
        ),
    ]
