# Generated by Django 5.1.3 on 2025-01-30 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0005_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaderuta',
            name='sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.sistema'),
        ),
    ]
