# Generated by Django 5.1.3 on 2025-01-30 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0006_hojaderuta_sistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fechaDeInicio', models.DateTimeField(blank=True, null=True)),
                ('fechaDeFin', models.DateTimeField(blank=True, null=True)),
                ('HojaDeRuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.hojaderuta')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.area')),
                ('programacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.programacion', verbose_name='programacion')),
            ],
        ),
    ]
