# Generated by Django 5.1.3 on 2025-01-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0008_frecuencia_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
    ]
