# Generated by Django 5.1.3 on 2025-02-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0009_alter_frecuencia_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='orden',
            field=models.IntegerField(null=True),
        ),
    ]
