# Generated by Django 5.1.3 on 2025-02-05 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0010_area_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='Activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.activo'),
        ),
    ]
