# Generated by Django 5.1.5 on 2025-02-07 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0011_ordendetrabajo_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='hojaderuta',
            name='horario',
        ),
        migrations.AddField(
            model_name='programacion',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms.horariopreestablecido'),
        ),
    ]
