# Generated by Django 5.1.5 on 2025-02-07 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0013_ordendetrabajo_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.marca')),
            ],
        ),
        migrations.CreateModel(
            name='KitDeHerramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('herramientas', models.ManyToManyField(related_name='kits_de_herramientas', to='cmms.herramienta')),
            ],
        ),
    ]
