# Generated by Django 5.1.5 on 2025-02-07 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0014_herramienta_kitdeherramientas'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaderuta',
            name='kitDeHerramientas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.kitdeherramientas'),
        ),
    ]
