# Generated by Django 5.1.5 on 2025-02-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0015_hojaderuta_kitdeherramientas'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitdeherramientas',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
