# Generated by Django 5.1.5 on 2025-02-07 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0016_kitdeherramientas_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.categoria'),
        ),
    ]
