# Generated by Django 5.1.5 on 2025-02-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0017_herramienta_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramienta',
            name='categoria',
        ),
        migrations.AddField(
            model_name='herramienta',
            name='categoria',
            field=models.ManyToManyField(blank=True, related_name='herramientas', to='cmms.categoria'),
        ),
    ]
