# Generated by Django 5.1.5 on 2025-02-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0019_personal_puesto_unidad_cuadrilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
