# Generated by Django 5.1.5 on 2025-02-10 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0020_herramienta_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.unidad'),
        ),
    ]
