# Generated by Django 5.1.3 on 2025-02-10 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0021_herramienta_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='marca',
            field=models.ForeignKey(default='Generico', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.marca'),
        ),
    ]
