# Generated by Django 5.1.3 on 2025-02-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0022_alter_herramienta_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='clave_kit',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
