# Generated by Django 5.1.3 on 2025-02-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0023_kit_clave_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitdeherramientas',
            name='clave_kit',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
