# Generated by Django 5.1.3 on 2025-02-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0024_kitdeherramientas_clave_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitdeherramientas',
            name='clave_kit',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
