# Generated by Django 5.1.3 on 2025-02-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0025_alter_kitdeherramientas_clave_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
