# Generated by Django 5.1.3 on 2025-02-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0026_alter_herramienta_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
