# Generated by Django 5.1.3 on 2025-02-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0027_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaderuta',
            name='clave_rutina',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
