# Generated by Django 5.1.3 on 2025-02-11 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0028_hojaderuta_clave_rutina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuadrilla',
            name='personal',
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='puestos',
            field=models.ManyToManyField(blank=True, related_name='cuadrillas', to='cmms.puesto'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='HorarioPreestablecido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.horariopreestablecido'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
