# Generated by Django 5.1.3 on 2025-02-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0030_herramienta_material_epp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EPP',
        ),
    ]
