# Generated by Django 5.1.3 on 2025-02-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0031_delete_epp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('REPUESTO', 'Repuesto'), ('EPP', 'EPP'), ('HERRAMIENTA', 'herramienta')], max_length=20),
        ),
    ]
