# Generated by Django 5.1.3 on 2025-02-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0032_alter_material_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaderuta',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='pasoshojaderuta',
            constraint=models.UniqueConstraint(fields=('paso', 'hojaderuta'), name='unique_paso_hojaderuta'),
        ),
    ]
