# Generated by Django 5.1.3 on 2025-02-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0033_alter_hojaderuta_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pasoshojaderuta',
            name='unique_paso_hojaderuta',
        ),
        migrations.AlterUniqueTogether(
            name='pasoshojaderuta',
            unique_together={('paso', 'hojaderuta')},
        ),
    ]
