# Generated by Django 5.1.3 on 2025-02-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0034_remove_pasoshojaderuta_unique_paso_hojaderuta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
