# Generated by Django 5.1.3 on 2025-02-14 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0036_categoriaherramienta_remove_herramienta_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramienta',
            name='categoria',
        ),
        migrations.AddField(
            model_name='herramienta',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmms.categoriaherramienta'),
        ),
    ]
