# Generated by Django 5.1.3 on 2025-02-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0037_remove_herramienta_categoria_herramienta_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitdeherramientas',
            name='herramientas',
            field=models.ManyToManyField(blank=True, related_name='kits_de_herramientas', to='cmms.herramienta'),
        ),
    ]
