# Generated by Django 5.1.5 on 2025-02-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0038_alter_kitdeherramientas_herramientas'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaderuta',
            name='ordenamiento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
