# Generated by Django 5.1.5 on 2025-02-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0039_hojaderuta_ordenamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
