# Generated by Django 5.1.5 on 2025-02-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0040_alter_programacion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasoshojaderuta',
            name='paso',
            field=models.CharField(max_length=500),
        ),
    ]
